version: '3.8'
services:
  server-load-balance:
    image: nginx:alpine
    container_name: server_load_balance_
    restart: always
    ports:
      - "80:80"  # Expõe a porta 80 para o balanceador de carga
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server_1
    networks:
      - loadbalancing

  server_1:
    build: ./app  # Usa o Dockerfile no diretório app/
    container_name: server_1
    restart: always
    environment:
      - HOSTNAME=server_1
    volumes:
      - ./app:/app  # Monta o código da aplicação para hot-reload
      - /app/node_modules  # Evita sobrescrever o node_modules no contêiner
    networks:
      - loadbalancing

  server_2:
    build: ./app  # Usa o Dockerfile no diretório app/
    container_name: server_2
    restart: always
    environment:
      - HOSTNAME=server_2
    volumes:
      - ./app:/app  # Monta o código da aplicação para hot-reload
      - /app/node_modules  # Evita sobrescrever o node_modules no contêiner
    networks:
      - loadbalancing

networks:
  loadbalancing:
    driver: bridge

